// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.minrat.grpc.proto.helloworld;

public interface DinnerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bocloud.grpc.proto.helloworld.DinnerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
