// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.minrat.grpc.proto.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_ByeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_ByeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_ByeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_ByeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_PayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_PayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_PayReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_PayReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_DrinkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_DrinkReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_KTVRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_KTVRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_KTVReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_KTVReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_GameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_GameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_GameReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_GameReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_DinnerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocloud_grpc_proto_helloworld_DinnerReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022!com.bocloud.grpc.pro" +
      "to.helloworld\"\034\n\014HelloRequest\022\014\n\004name\030\001 " +
      "\001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t\"\032\n\nBy" +
      "eRequest\022\014\n\004name\030\001 \001(\t\"\033\n\010ByeReply\022\017\n\007me" +
      "ssage\030\001 \001(\t\"\032\n\nPayRequest\022\014\n\004name\030\001 \001(\t\"" +
      "\033\n\010PayReply\022\017\n\007message\030\001 \001(\t\"\034\n\014DrinkReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"\035\n\nDrinkReply\022\017\n\007mess" +
      "age\030\001 \001(\t\"\032\n\nKTVRequest\022\014\n\004name\030\001 \001(\t\"\033\n" +
      "\010KTVReply\022\017\n\007message\030\001 \001(\t\"\033\n\013GameReques" +
      "t\022\014\n\004name\030\001 \001(\t\"\034\n\tGameReply\022\017\n\007message\030",
      "\001 \001(\t\"\035\n\rDinnerRequest\022\014\n\004name\030\001 \001(\t\"\036\n\013" +
      "DinnerReply\022\017\n\007message\030\001 \001(\t2w\n\007Greeter\022" +
      "l\n\010SayHello\022/.com.bocloud.grpc.proto.hel" +
      "loworld.HelloRequest\032-.com.bocloud.grpc." +
      "proto.helloworld.HelloReply\"\0002q\n\007GoodBye" +
      "\022f\n\006SayBye\022-.com.bocloud.grpc.proto.hell" +
      "oworld.ByeRequest\032+.com.bocloud.grpc.pro" +
      "to.helloworld.ByeReply\"\0002r\n\003Pay\022k\n\013Consu" +
      "merPay\022-.com.bocloud.grpc.proto.hellowor" +
      "ld.PayRequest\032+.com.bocloud.grpc.proto.h",
      "elloworld.PayReply\"\0002v\n\005Drink\022m\n\tHaveDri" +
      "nk\022/.com.bocloud.grpc.proto.helloworld.D" +
      "rinkRequest\032-.com.bocloud.grpc.proto.hel" +
      "loworld.DrinkReply\"\0002l\n\003KTV\022e\n\005GoKTV\022-.c" +
      "om.bocloud.grpc.proto.helloworld.KTVRequ" +
      "est\032+.com.bocloud.grpc.proto.helloworld." +
      "KTVReply\"\0002w\n\rEntertainment\022f\n\004Game\022..co" +
      "m.bocloud.grpc.proto.helloworld.GameRequ" +
      "est\032,.com.bocloud.grpc.proto.helloworld." +
      "GameReply\"\0002z\n\006Dinner\022p\n\nHaveDinner\0220.co",
      "m.bocloud.grpc.proto.helloworld.DinnerRe" +
      "quest\032..com.bocloud.grpc.proto.helloworl" +
      "d.DinnerReply\"\000B6\n!com.bocloud.grpc.prot" +
      "o.helloworldB\017HelloWorldProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bocloud_grpc_proto_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bocloud_grpc_proto_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bocloud_grpc_proto_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_ByeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bocloud_grpc_proto_helloworld_ByeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_ByeRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_ByeReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bocloud_grpc_proto_helloworld_ByeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_ByeReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_PayRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_bocloud_grpc_proto_helloworld_PayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_PayRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_PayReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_bocloud_grpc_proto_helloworld_PayReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_PayReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_DrinkRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_bocloud_grpc_proto_helloworld_DrinkReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_DrinkReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_KTVRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_bocloud_grpc_proto_helloworld_KTVRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_KTVRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_KTVReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_bocloud_grpc_proto_helloworld_KTVReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_KTVReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_GameRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_bocloud_grpc_proto_helloworld_GameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_GameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_GameReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_bocloud_grpc_proto_helloworld_GameReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_GameReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_DinnerRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerReply_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_bocloud_grpc_proto_helloworld_DinnerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocloud_grpc_proto_helloworld_DinnerReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
