// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.minrat.grpc.proto.helloworld;

public interface KTVReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bocloud.grpc.proto.helloworld.KTVReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
